Repository astral-sh/python-build-standalone, pull requests merged in 2024-12, with the labels that each got.

#395 Use relocatable shebang with space-in-path robustness
  cpython-unix/build-cpython.sh
Labels: bug

#422 Remove `-Werror=unguarded-availability-new` from `sysconfig` data
  cpython-unix/build-cpython.sh
Labels: enhancement

#434 Remove Tkl/tk caveats from quirks
  docs/quirks.rst
Labels: documentation

#429 Pass `-utf8` to `vswhere`
  cpython-windows/build.py
Labels: platform:windows

#427 Ignore clean-up errors for Windows temporary directory
  cpython-windows/build.py
Labels: platform:windows

#432 Use larger GitHub Windows runner
  .github/workflows/windows.yml
Labels: platform:windows

#436 Skip builds on `ci:skip` or `documentation` labels
  ci-matrix.py
Labels: ci:skip

#437 Add `ci:dry-run` to skip performing builds but still test the matrix
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  ci-matrix.py
Labels: ci:dry-run

#438 Only run the image builds if we are doing Linux Python builds
  .github/workflows/linux.yml
Labels: internal, platform:linux, ci:dry-run

#439 Fix `any_builds` CI check on Linux
  .github/workflows/linux.yml
Labels: platform:linux, ci:dry-run

#441 Use single quotes for labels in shell call
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: internal, ci:dry-run

#444 Remove pgo-only builds on macOS and Linux
  ci-targets.yaml
  src/release.rs
Labels: build:pgo

#446 Use a larger runner for the release process
  .github/workflows/release.yml
Labels: internal, ci:skip

#448 Restore `depot-macos-latest` usage for macOS
  .github/workflows/apple.yml
Labels: internal, platform:darwin

#450 Drop pgo-only free-threaded macOS buid from expected release triples
  src/release.rs
Labels: internal, ci:skip

#440 Skip building `pythonbuild` when not needed
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  src/github.rs
Labels: internal, platform:windows, ci:dry-run

#445 Some cosmetic changes to the workflow names
  .github/workflows/check.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: ci:dry-run

#443 Add support for Python 3.14 on macOS and GNU Linux
  ci-matrix.py
  ci-targets.yaml
  cpython-unix/Makefile
  cpython-unix/build-cpython.sh
  cpython-unix/build-main.py
  cpython-unix/build.py
  cpython-unix/extension-modules.yml
  cpython-unix/patch-dont-clear-runshared-14.patch
  cpython-unix/targets.yml
  pythonbuild/cpython.py
  pythonbuild/downloads.py
  src/validation.rs
Labels: platform:darwin, platform:linux, arch:x86_64, libc:gnu, python:3.14

#452 Apply readelf patch for cross-compiling on older Python versions
  cpython-unix/build-cpython.sh
  cpython-unix/patch-apple-cross.patch
  cpython-unix/patch-cross-readelf.patch
Labels: internal, platform:linux

#453 Use Python 3.12 to run builds on Windows
  .github/workflows/windows.yml
Labels: internal, platform:windows

#458 Show Docker build errors when available
  pythonbuild/docker.py
Labels: internal, ci:skip
