Repository astral-sh/python-build-standalone, pull requests merged in 2025-09, with the labels that each got.

#780 On macOS, add 64 bytes of headerpad to accommodate code signatures
  cpython-unix/build-cpython.sh
  src/validation.rs
Labels: platform:darwin, platform:linux, python:3.13, build:debug, arch:x86_64, arch:aarch64

#786 Update SQLite to 3.50.4
  pythonbuild/downloads.py
  src/verify_distribution.py
Labels: python:3.13

#781 Run `cargo fmt` and `cargo clippy --fix`
  src/github.rs
  src/macho.rs
  src/main.rs
  src/release.rs
  src/validation.rs
Labels: python:3.12, arch:aarch64

#653 Add loongarch64-linux support
  cpython-unix/base.Dockerfile
  cpython-unix/base.debian9.Dockerfile
  cpython-unix/build-cpython.sh
  cpython-unix/build-libX11.sh
  cpython-unix/build-libxcb.sh
  cpython-unix/build-main.py
  cpython-unix/build-ncurses.sh
  cpython-unix/build-xorgproto.sh
  cpython-unix/build.Dockerfile
  cpython-unix/build.cross-loongarch64.Dockerfile
  cpython-unix/build.cross-riscv64.Dockerfile
  cpython-unix/build.cross.Dockerfile
  cpython-unix/extension-modules.yml
  cpython-unix/patch-configure-add-loongarch-triplet.patch
  cpython-unix/targets.yml
  docs/building.rst
Labels: platform:linux

#795 macOS CI: Stop setting $APPLE_SDK_PATH
  .github/workflows/macos.yml
Labels: platform:darwin, python:3.9, python:3.14
