Repository astral-sh/python-build-standalone, pull requests merged in 2025-08, with the labels that each got.

#726 Bump CPython 3.13 version to 3.13.6
  cpython-unix/build-cpython.sh
  cpython-unix/patch-uuid-getnode-stable-3.13.patch
  pythonbuild/downloads.py
Labels: python:3.13

#731 Fix label subsetting
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: ci:skip

#729 Persist credentials in the release workflow
  .github/workflows/release.yml
Labels: ci:skip

#733 Use a larger runner again for the release
  .github/workflows/release.yml
Labels: ci:skip

#732 Add more artifacts to the skip list
  src/github.rs
Labels: ci:skip

#747 Build _ctypes_test as a shared module (fixes #721)
  cpython-unix/extension-modules.yml
  src/validation.rs
Labels: platform:darwin, platform:linux, python:3.9, arch:x86_64, arch:aarch64

#759 Bump CPython to 3.13.7
  pythonbuild/downloads.py
Labels: python:3.13

#706 Fix download statistics
  pythonbuild/utils.py
  requirements.dev.in
  requirements.dev.txt
  requirements.in
  requirements.txt
  requirements.win.txt
Labels: ci:skip
