Repository astral-sh/python-build-standalone, pull requests merged in 2025-07, with the labels that each got.

#682 Add zstd support for Python 3.14+ on Unix
  cpython-unix/Makefile
  cpython-unix/build-cpython.sh
  cpython-unix/build-zstd.sh
  cpython-unix/build.py
  cpython-unix/extension-modules.yml
  cpython-unix/targets.yml
  src/validation.rs
Labels: platform:darwin, platform:linux, python:3.13, ci:skip, python:3.14

#667 Bump SQLite to `3.49.1.0`
  cpython-unix/build-sqlite.sh
  pythonbuild/downloads.py
  src/verify_distribution.py
Labels: python:3.13

#689 Bump to 3.14.0b4
  cpython-unix/build-cpython.sh
  cpython-unix/patch-jit-cflags-314.patch
  pythonbuild/downloads.py
Labels: python:3.14

#691 Drop `.sha256` files from releases
  src/github.rs
Labels: ci:skip

#695 Add missing Makefile dependency for binutils -> gcc image (#692)
  cpython-unix/Makefile
Labels: ci:skip

#701 Further fix sqlite test cases
  src/verify_distribution.py
Labels: ci:skip

#709 Run dependabot monthly instead of weekly
  .github/dependabot.yml
Labels: ci:skip
