Repository astral-sh/python-build-standalone, pull requests merged in 2025-05, with the labels that each got.

#580 Bump to 3.14.0a7
  cpython-unix/extension-modules.yml
  cpython-windows/build.py
  pythonbuild/downloads.py
  src/validation.rs
Labels: platform:windows, python:3.14

#614 Fix zlib-ng project expectation for <3.14
  cpython-windows/build.py
Labels: platform:windows

#583 Include free-threaded Python in published musl distributions
  .github/workflows/release.yml
  src/release.rs
Labels: ci:skip

#544 Allow enabling the JIT on aarch64 macOS
  cpython-unix/build-cpython.sh
  cpython-unix/patch-jit-cflags-313.patch
  cpython-unix/patch-jit-cflags-314.patch
Labels: platform:darwin, python:3.13, build:pgo, python:3.14

#621 Add an rpath to bin/python3 on glibc platforms to fix #619
  cpython-unix/build-cpython.sh
Labels: platform:linux

#615 Use larger runner for releases
  .github/workflows/release.yml
Labels: ci:skip

#622 Disable unsafe identical code folding in BOLT
  cpython-unix/build-cpython.sh
  cpython-unix/patch-configure-bolt-icf-safe.patch
Labels: platform:linux
