Repository astral-sh/python-build-standalone, pull requests merged in 2025-01, with the labels that each got.

#460 Configure `pkg-config` during CPython builds
  cpython-unix/build-cpython.sh
Labels: platform:darwin, platform:linux

#463 unix: BOLT fixes
  cpython-unix/build-cpython.sh
  cpython-unix/patch-configure-bolt-flags.patch
  cpython-unix/patch-test-embed-prevent-segfault-3.14.patch
  cpython-unix/patch-test-embed-prevent-segfault.patch
Labels: platform:darwin, platform:linux

#365 Bump autoconf from 2.71 -> 2.72
  pythonbuild/downloads.py
Labels: dependencies

#467 ci: enable PGO on x86-64-v4
  ci-targets.yaml
Labels: platform:linux, arch:x86_64

#357 Bump zlib from 1.2.13 -> 1.3.1
  pythonbuild/downloads.py
Labels: dependencies

#471 Bump Docker timeout from 60s to 10m
  cpython-unix/build.py
Labels: platform:linux, python:3.13, arch:aarch64

#474 Update expected release triples for `x86_64_v4`
  src/release.rs
Labels: ci:skip

#475 Update release distribution fetch script to include `darwin.yml`
  src/github.rs
Labels: internal, ci:skip

#476 Update release distribution fetch script to include `macos.yml`
  src/github.rs
Labels: ci:skip

#477 Update release targets for x86_64 musl
  src/release.rs
Labels: ci:skip

#480 Update comments in release workflow
  .github/workflows/release.yml
Labels: ci:skip

#483 Generate CI runners for build matrix dynamically
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  ci-matrix.py
  ci-runners.yaml
Labels: ci:dry-run

#482 Fix x86_64-apple-darwin comment in targets.yml
  cpython-unix/targets.yml
Labels: ci:skip

#468 unix: call `ulimit -n` to avoid overheads
  cpython-unix/base.Dockerfile
  cpython-unix/build.Dockerfile
  cpython-unix/gcc.Dockerfile
  cpython-unix/xcb.Dockerfile
Labels: internal

#486 Retry on transient failures during artifact upload
  Cargo.lock
  Cargo.toml
  src/github.rs
Labels: ci:skip

#492 Implement matrix sharding
  .github/workflows/linux.yml
  ci-matrix.py
Labels: ci:dry-run

#491 Add riscv64-linux support
  .github/workflows/linux.yml
  ci-targets.yaml
  cpython-unix/build-cpython.sh
  cpython-unix/build-libX11.sh
  cpython-unix/build-main.py
  cpython-unix/build.cross-riscv64.Dockerfile
  cpython-unix/build.py
  cpython-unix/extension-modules.yml
  cpython-unix/targets.yml
  cpython-unix/xcb.cross-riscv64.Dockerfile
  docs/building.rst
  src/release.rs
  src/validation.rs
Labels: platform:linux, arch:riscv64

#496 Retry downloads when <75% of the file is downloaded
  pythonbuild/utils.py
Labels: platform:linux, python:3.13

#495 Upgrade tcl/tk from 8.6.12 to 8.6.14 on Unix
  cpython-unix/build-cpython.sh
  cpython-unix/build.py
  cpython-unix/extension-modules.yml
  cpython-windows/build.py
  pythonbuild/downloads.py
  src/validation.rs
Labels: dependencies

#494 Add Python 3.14 support on Windows
  ci-targets.yaml
  cpython-windows/build.py
  src/validation.rs
Labels: platform:windows, python:3.14

#497 Add Python 3.14 to Windows release targets
  src/release.rs
Labels: ci:skip

#498 Fix attestation permissions for sharded linux builds
  .github/workflows/linux.yml
Labels: ci:skip

#500 Upgrade `reqwest` to 0.12
  Cargo.lock
  Cargo.toml
  src/github.rs
Labels: ci:skip

#505 Fix virtual environment creation when bootstrapping build environments with a standalone Python
  build-linux.py
Labels: platform:linux, python:3.13

#507 Make the installed pkg-config files relocatable (astral-sh/uv#11028)
  cpython-unix/build-cpython.sh
  docs/quirks.rst
Labels: platform:darwin, platform:linux, python:3.13

#506 build-cpython.sh: Don't repack the pip wheel
  cpython-unix/build-cpython.sh
Labels: internal
